[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "NeerCore"
authors = [{name = "jurilents", email = "keeeneeek@gmail.com"}]
dynamic = ["version", "description"]
